Controllers/HomeController.cs
using ClassManegmentSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Protocol.Plugins;
using System.Diagnostics;

namespace ClassManegmentSystem.Controllers
{
    public class HomeController : Controller
    {

        private readonly AppDbContext _Context;

        public HomeController(AppDbContext Context)
        {
            _Context = Context;
        }

        private IEnumerable<Class> Class()
        {
            var Class = _Context.classes.Include(e => e.teacher).Include(e => e.student).Include(e => e.student.city).ToList();
            return Class;
        }

        public IActionResult Index()
        {
            var Classes = new List<Class>();
            return View(Tuple.Create(Class(), Classes));


        }
        [HttpPost]
        public IActionResult Index(string TeacherName)
        {
            var Classes = Class().Where(e=> TeacherName == e.teacher.TeacherName).DistinctBy(e=>e.ClassNumber).ToList();
           

            return View(Tuple.Create(Class(),Classes)); 
        }


        public IActionResult Register()
        {
            return View();
        }
       
       

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SchoolClassController.cs
using ClassManegmentSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClassManegmentSystem.Controllers
{
    public class SchoolClassController : Controller
    {

        private readonly AppDbContext _Context;

        public SchoolClassController(AppDbContext Context)
        {
            _Context = Context;
        }
        private IEnumerable<Class> Class()
        {
            var Class = _Context.classes.Include(e => e.teacher).Include(e => e.student).Include(e => e.student.city).Include(e=>e.Attendees).ToList();
            return Class;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetTeacherClass()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(int Studentid,int Teacherid)
        {
            try
            {
                Class Class = new()
                {
                    StudentId = Studentid,
                    TeacherId = Teacherid,
                };

                Class.student = _Context.Students.Include(e => e.city).FirstOrDefault(e => e.StudentId == Class.StudentId);
                Class.teacher = _Context.Teachers.FirstOrDefault(e => e.TeacherId == Class.TeacherId);
                Class.ClassSubject = Class.teacher.Subject;
                Class.ClassName = Class.teacher.TeacherName + "'s Class in " + Class.student.city.CityName + ", Grade: " + Class.student.StudentGrade + ", Subject: " + Class.ClassSubject;
                Class.ClassNumber = Class.teacher.TeacherId + "-" + Class.student.city.CityId + "-" + Class.student.StudentGrade;
                try
                {
                    _Context.Add(Class);
                    _Context.SaveChanges();
                }
                catch {return RedirectToAction("Error" ,"Home");}

                return RedirectToAction("Table", new { Id = Class.ClassNumber });
            }
            catch { return RedirectToAction("Index", "Students"); }
        }

        public IActionResult Table(string Id)
        {

            var ClassData = Class().Where(e => e.ClassNumber == Id);
            var cc = Class().FirstOrDefault(e => e.ClassNumber == Id);
            var StudentData = ClassData.Select(e => e.student).ToList();

            if (!(StudentData is null))
            {
                //selected just the students of the filter
                ViewBag.Students = _Context.Students.Where(e => e.StudentGrade == cc.student.StudentGrade && e.city.CityName == cc.student.city.CityName).ToList();
                //to take the Teacher data with me, not the best way but it works till i learn the other one
                ViewBag.Teacher = Class().FirstOrDefault(e => e.teacher.TeacherName == cc.teacher.TeacherName).teacher;
                var Attendees = _Context.Attendees.Where(e => e.TeacherId == cc.teacher.TeacherId).ToList();

                return View(Tuple.Create(StudentData, Attendees));
            }
            return RedirectToAction("Index" , "Home");
        }
        [HttpPost]
        public IActionResult Table(int TeacherId , int StudentId , DateTime AttendDate)
        {
            var Class = _Context.classes.FirstOrDefault(e=> e.TeacherId == TeacherId && e.StudentId == StudentId);
            if (!(Class is null)) {
                var Attend = new Attendees()
                {
                    TeacherId = TeacherId,
                    StudentId = StudentId,
                    ClassNumber = Class.ClassNumber,
                    DateOfAttendeens = AttendDate
                };
                Attend.Class = _Context.classes.FirstOrDefault(e => e.TeacherId == TeacherId && e.StudentId == StudentId);
                if (ModelState.IsValid)
                {
                    _Context.Add(Attend);
                    _Context.SaveChanges();
                }
            return RedirectToAction("Table", new { Id = Class.ClassNumber});
            }
            return View("Error", "Home");
        }











    }
}

Controllers/StudentsController.cs
using ClassManegmentSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClassManegmentSystem.Controllers
{
    public class StudentsController : Controller
    {
        private readonly AppDbContext _Context;

        public StudentsController(AppDbContext Context)
        {
            _Context = Context;
        }
        private IEnumerable<Student> students()
        {
            return _Context.Students.Include(m=> m.city);
        }

        public IActionResult Index()
        {
            return View(students());
        }

        [HttpGet]
        public IActionResult Create()
        {
            //sending the cities so make a dropdown out of it
            ViewBag.Cities = _Context.cities.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Student student)
        {
            //makes sure every thing is ok
            if (ModelState.IsValid)
            {
                _Context.Students.Add(student);
                _Context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        public IActionResult Edit(int id)
        {
     
            var student = students().FirstOrDefault(s => s.StudentId == id);
            ViewBag.Cities = _Context.cities.ToList();
            return View(student);
        }

        [HttpPost]
        public IActionResult Edit(Student student)
        {

            if (ModelState.IsValid)
            {
                _Context.Students.Update(student);
                student.CreationDate = DateTime.Now;
                _Context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        [HttpGet]
        public IActionResult Info(int id)
        {
            var student = students().FirstOrDefault(s => s.StudentId == id);
            var listofids = _Context.classes.Where(e => e.StudentId == id).Select(e => e.teacher);
            ViewBag.TeacherIds = listofids.ToList();
            ViewBag.AllTeacherIds = _Context.Teachers.ToList();
            ViewBag.boo = listofids.Any();
            ViewBag.Cities = _Context.cities.ToList();
            return View(student);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var student = students().FirstOrDefault(s => s.StudentId == id);
            if (ModelState.IsValid)
            {
                _Context.Students.Remove(student);
                _Context.SaveChanges();
                return Ok();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassManegmentSystem.Models;

namespace ClassManegmentSystem.Controllers
{
    public class TeachersController : Controller
    {
        private readonly AppDbContext _context;

        public TeachersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
              return _context.Teachers != null ? 
                          View(await _context.Teachers.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Teachers'  is null.");
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.TeacherId == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeacherId,TeacherName,TeacherNationalID,TeacherPhoneNumber,Age,Subject")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeacherId,TeacherName,TeacherNationalID,TeacherPhoneNumber,Age,Subject")] Teacher teacher)
        {
            if (id != teacher.TeacherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                //    if (!TeacherExists(Convert.ToString(teacher.TeacherId)))
                //    {
                //        return NotFound();
                //    }
                //    else
                //    {
                //        throw;
                //    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.TeacherId == id);
            if (teacher == null)
            {
                return NotFound();
            }
            _context.Teachers.Remove(teacher);
            _context.SaveChanges();
            return Ok();
        }

        //// POST: Teachers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(string id)
        //{
        //    if (_context.Teachers == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.Teachers'  is null.");
        //    }
        //    var teacher = await _context.Teachers.FindAsync(id);
        //    if (teacher != null)
        //    {
        //        _context.Teachers.Remove(teacher);
        //    }
            
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool TeacherExists(int id)
        {
          return (_context.Teachers?.Any(e => e.TeacherId == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@model Tuple<IEnumerable<ClassManegmentSystem.Models.Class>,List<ClassManegmentSystem.Models.Class>>
@{
    ViewData["Title"] = "Home Page";

    var Teacher = Model.Item1.Select(e =>e.teacher.TeacherName).Distinct().ToList();
    var Grade = Model.Item1.Select(e => e.student.StudentGrade).Distinct().ToList();
    var City = Model.Item1.Select(e => e.student.city.CityName).Distinct().ToList();
    var Groups = ViewBag.Classes;

}

<div class="text-center">
    <h1 class="display-4 text-primary">Welcome </h1>
    <p class="text-primary opacity-50 fw-bold">Choose the Teacher you want to see his Classes</p>
</div>
<br/>




<form asp-action="Index" asp-controller="Home" method="post">
<div class=" d-flex flex-row justify-content-around ">
        <div class="col-3"> @Html.Label("TeacherName") @Html.DropDownList("TeacherName", new SelectList(Teacher) ,"",new { @class = "form-control"})</div>

      @*  <div class="col-2"> @Html.Label("Grade") @Html.DropDownList("Grade", new SelectList(Grade) ,"",new { @class = "form-control" })</div>
        <div class="col-3"> @Html.Label("CityName") @Html.DropDownList("CityName", new SelectList(City) ,"",new { @class = "form-control"  })</div>*@
</div>
    <div class="d-flex align-items-center justify-content-center mt-4">
        @*<a asp-action="Table" class="btn btn-outline-primary">Filter</a>*@

        <input type="submit"value="Filter" class="btn btn-outline-primary" />
</div>
</form>
<br/>
@if (Model.Item2.Any())
{
    @foreach (var item in Model.Item2)
    {
        <div class="card d-flex justify-content-between align-content-around" style="width: 18rem;">
                <div class="card-body ">
                    <h5 class="card-title">@item.student.city.CityName</h5>
                    <p class="card-text">@item.ClassName</p>
                    <a asp-controller="SchoolClass" asp-action="Table"  asp-route-Id ="@item.ClassNumber"  class="card-link">Table Of Students</a>
                </div>
            </div>
    }
}else{
    <div class="alert alert-warning d-flex align-items-lg-center mt-5 col-12" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle me-2" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z" />
        </svg>
        <div>
           Select the teacher to view to classes he has
        </div>
    </div>
}

@*if(!Model.Any()){
    <div class="alert alert-warning d-flex align-items-lg-center mt-5 col-12" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle me-2" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z" />
        </svg>
        <div>
            Set some filtration to create your table
        </div>
    </div>
}
}*@

Views/Home/Register.cshtml
@{
    ViewData["Title"] = "Login Page";
}

<div class="text-center">
    <h1 class="display-4 text-primary">Welcome</h1>
    <p class="text-primary opacity-50 fw-bold">please choose the Account type to Register </p>
</div>
<br />



<div class="d-flex justify-content-around ">
    <div class="card" style="width: 18rem;">
        <img src="~/teacher-concept-illustration_114360-2166.jpg" />
        <div class="card-body">
            <h5 class="card-title">Register as a Teacher</h5>
            <p class="card-text">Some steps to register your student account</p>
            <a asp-controller="Teachers" asp-action="Create" class="btn btn-primary">Register</a>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="~/istockphoto-1171911961-170667a.jpg" />

        <div class="card-body">
            <h5 class="card-title">Register as a Student</h5>
            <p class="card-text">Some steps to register your student account</p>
            <a asp-controller="Students" asp-action="Create" class="btn btn-primary">Register</a>
        </div>
    </div>
</div>

Views/Home/Table.cshtml
@model IEnumerable<ClassManegmentSystem.Models.Student>
@{

    ViewData["Title"] = "Home Page";
    //var TeacherData = Model.Select(e => new { e.teacher.TeacherName, e.teacher.TeacherId , e.teacher.Subject }).Distinct().ToList();
        int count = Model.Select(e => e.StudentName).Count();
        string city = Model.FirstOrDefault(e => true).city.CityName;
        string grade = Model.FirstOrDefault(e => true).StudentGrade;
    

}

<div class="text-center">
</div>
<br />
<br />

@*@foreach (var item in Model)
{
    <div class="d-flex justify-content-between align-content-center text-primary" >

    <h3>Mr/@item.teacher.TeacherName</h3>
    <h3>Subject: @item.teacher.Subject</h3>
        <h3> Count of Students: @count</h3>

    </div>
    
}   *@

<div class="d-flex justify-content-between align-content-center text-primary" >

    <h3>Mr/@ViewBag.Teacher.TeacherName</h3>
    <h3>Subject: @ViewBag.Teacher.Subject - ID = @ViewBag.Teacher.TeacherId</h3>
        <h3> Count of Students: @count</h3>

    </div>
    


<br />
@if (Model.Any())
{
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.StudentName)</th>
                    <th>@Html.DisplayNameFor(model => model.city.CityName)</th>
                    <th>@Html.DisplayNameFor(model => model.StudentNumber)</th>
                    <th>@Html.DisplayNameFor(model => model.StudentPhoneNumber)</th>
                    <th>@Html.DisplayNameFor(model => model.StudentParentPhoneNumber)</th>
                    <th>@Html.DisplayNameFor(model => model.StudentGrade)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                      
                        <td>@Html.DisplayFor(model => item.StudentName)</td>
                        <td>@Html.DisplayFor(model => item.city.CityName)</td>
                        <td>@Html.DisplayFor(model => item.StudentNumber)</td>
                        <td>@Html.DisplayFor(model => item.StudentPhoneNumber)</td>
                        <td>@Html.DisplayFor(model => item.StudentParentPhoneNumber)</td>
                        <td>@Html.DisplayFor(model => item.StudentGrade)</td>
                    </tr>
                }
            </tbody>
        </table>
        <br/>
       

    </div>
} 

@if (!Model.Any())
{
    <div class="alert alert-warning d-flex align-items-lg-center mt-5 col-12" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle me-2" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z" />
        </svg>
        <div>
            Set some filtration to create your table
        </div>
    </div>
    <br/>
}
<form method="post" asp-action="Create">
            <div>
                <dt class="col-sm-3">
                    @Html.DisplayName("Add To more students to class")
                </dt>
                <dd class="col-sm-3 mt-2">
                    @Html.DropDownList("StudentId", new SelectList(ViewBag.Students, "StudentId", "StudentName"),"", new { @class = "form-control" , @placeholder = "Student's id to attend to his class..."})
                </dd>
            </div>
         
				<div class="d-none">
					<dt class="col-sm-2 mt-2 ">
						@Html.DisplayName("Add To Class")
					</dt>
					<dd class="col-sm-3">
                    <input name="TeacherId" value="@ViewBag.Teacher.TeacherId" />
                        @Html.TextBox("TeacherId", null, new { @class = "form-control" , @placeholder = "Teacher's id to attend to his class..."})
					</dd>
				</div>
				<div class="form-group">

                    <input type="submit" value="Add" class="btn btn-primary"  />
				</div>
            
          
        </form>
@*

<div class="d-flex justify-content-around ">
<div class="card" style="width: 18rem;">
<img src="~/teacher-concept-illustration_114360-2166.jpg" />
  <div class="card-body">
    <h5 class="card-title">Teachers Portal</h5>
    <p class="card-text">As a teacher you go here.</p>
            <a href="#" class="btn btn-primary">go to Teachers</a>
  </div>
</div>
	<div class="card" style="width: 18rem;">
		<img src="~/istockphoto-1171911961-170667a.jpg" />

    <div class="card-body">
        <h5 class="card-title">Students Portal</h5>
            <p class="card-text">As a student you go here.</p>
            <a asp-action="" class="btn btn-primary">go to Students</a>
    </div>
</div>
</div>*@